import { Link } from 'wouter';
import { ArrowDownRight, ArrowRight, Check, CircleDollarSign, Leaf, LineChart, ShieldCheck, Sparkles } from 'lucide-react';
import { BrandMark, PublicNav } from '@/components/moneywise-shell';

export default function Landing() {
  return (
    <div className="paper-noise min-h-[100dvh] overflow-hidden bg-background">
      <PublicNav />
      <main>
        <section className="relative mx-auto max-w-7xl px-5 pb-24 pt-12 md:px-8 md:pb-36 md:pt-24">
          <div className="money-grid absolute inset-x-0 top-0 h-[650px] opacity-75" />
          <div className="absolute -left-48 top-32 h-96 w-96 rounded-full bg-[hsl(var(--primary)/.13)] blur-3xl" />
          <div className="relative grid items-center gap-16 lg:grid-cols-[1.02fr_.98fr]">
            <div className="max-w-2xl">
              <div className="animate-rise-in inline-flex items-center gap-2 rounded-full border border-[hsl(var(--secondary)/.35)] bg-[hsl(var(--secondary)/.06)] px-3 py-1.5 text-xs font-bold uppercase tracking-[0.14em] text-[hsl(var(--secondary))]"><span className="h-1.5 w-1.5 rounded-full bg-[hsl(var(--secondary))] shadow-[0_0_10px_hsl(var(--secondary))]" /> Private finance cockpit</div>
              <h1 className="animate-rise-in delay-1 display-font mt-7 max-w-[700px] text-[clamp(3.5rem,8vw,7.5rem)] font-bold leading-[.88] tracking-[-.09em] text-foreground">Make the <em className="font-bold text-primary">numbers</em> tell the truth.</h1>
              <p className="animate-rise-in delay-2 mt-8 max-w-lg text-lg leading-relaxed text-muted-foreground md:text-xl">Moneywise turns a noisy month into a clean read on what came in, what went out, and what your next decision can be.</p>
              <div className="animate-rise-in delay-3 mt-9 flex flex-wrap items-center gap-4"><Link href="/sign-up" className="group flex items-center gap-3 rounded-xl bg-primary px-5 py-3.5 text-sm font-bold text-primary-foreground shadow-[0_0_28px_hsl(var(--primary)/.22)] transition-transform hover:-translate-y-1" data-testid="link-hero-start">Open your cockpit <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link><Link href="/sign-in" className="rounded-xl border border-border px-3 py-3.5 text-sm font-bold text-foreground transition-colors hover:border-[hsl(var(--secondary)/.6)] hover:text-[hsl(var(--secondary))]" data-testid="link-hero-sign-in">I already have an account</Link></div>
            </div>
            <div className="relative mx-auto w-full max-w-[500px] lg:mr-0">
              <div className="absolute -right-10 -top-8 h-36 w-36 rounded-full bg-[hsl(var(--primary)/.26)] blur-2xl animate-soft-pulse" />
              <div className="scan-overlay neon-edge relative rotate-[2deg] rounded-[2rem] border border-[hsl(var(--secondary)/.28)] bg-[hsl(var(--card)/.86)] p-5 shadow-[0_25px_70px_hsl(222_45%_3%/.35)] backdrop-blur-xl md:p-7">
                 <div className="flex items-center justify-between"><div><p className="mono-font text-[10px] font-bold uppercase tracking-[.14em] text-[hsl(var(--secondary))]">Workspace / first run</p><p className="display-font mt-1 text-2xl font-bold">Ready for your data</p></div><div className="grid h-10 w-10 place-items-center rounded-full border border-[hsl(var(--secondary)/.4)] bg-[hsl(var(--secondary)/.12)] text-[hsl(var(--secondary))]"><LineChart className="h-5 w-5" /></div></div>
                 <div className="mt-8 rounded-2xl border border-[hsl(var(--primary)/.45)] bg-[hsl(var(--primary)/.14)] p-5 text-foreground"><p className="mono-font text-[10px] font-semibold uppercase tracking-[.15em] text-primary">Net profit</p><p className="display-font mt-1 text-4xl font-bold text-primary">$0<span className="text-xl">.00</span></p><div className="mt-5 flex items-center justify-between border-t border-[hsl(var(--primary)/.18)] pt-4 text-xs"><span className="text-muted-foreground">nothing logged yet</span><span className="font-bold text-[hsl(var(--secondary))]">start clean</span></div></div>
                 <div className="mt-6 flex h-[88px] items-end gap-2.5 border-b border-border pb-5">{Array.from({ length: 8 }, (_, i) => <div key={i} className="h-px flex-1 bg-border" />)}</div>
                 <div className="mt-5 space-y-3"><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 font-medium text-muted-foreground"><span className="h-2.5 w-2.5 rounded-full border border-primary/60" /> No expenses yet</span><span className="mono-font text-xs text-muted-foreground">$0.00</span></div><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 font-medium text-muted-foreground"><span className="h-2.5 w-2.5 rounded-full border border-secondary/60" /> Your first signal</span><span className="mono-font text-xs text-muted-foreground">$0.00</span></div></div>
              </div>
               <div className="absolute -bottom-6 -left-8 flex items-center gap-3 rounded-2xl border border-[hsl(var(--secondary)/.3)] bg-card/90 px-4 py-3 shadow-xl backdrop-blur"><div className="grid h-9 w-9 place-items-center rounded-full bg-[hsl(var(--secondary)/.14)] text-[hsl(var(--secondary))]"><Check className="h-4 w-4" /></div><div><p className="text-xs font-bold">Private by default</p><p className="text-[11px] text-muted-foreground">Your first entry stays yours</p></div></div>
            </div>
          </div>
        </section>
        <section className="border-y border-border bg-[hsl(var(--card)/.45)] px-5 py-10 md:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-6"><p className="max-w-sm text-sm font-semibold leading-relaxed text-muted-foreground">A sharper relationship with money starts with a sharper read.</p><div className="flex flex-wrap gap-x-9 gap-y-3 text-xs font-bold uppercase tracking-[.13em] text-muted-foreground/75"><span className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[hsl(var(--secondary))]" /> Private by default</span><span className="flex items-center gap-2"><Leaf className="h-4 w-4 text-primary" /> No judgment here</span><span className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-[hsl(var(--secondary))]" /> Built for real life</span></div></div></section>
        <section className="mx-auto max-w-7xl px-5 py-24 md:px-8 md:py-36"><div className="grid gap-16 md:grid-cols-[.65fr_1.35fr]"><div><p className="mono-font text-xs font-bold uppercase tracking-[.18em] text-[hsl(var(--secondary))]">The readout</p><h2 className="display-font mt-4 max-w-md text-5xl font-bold leading-[.92] tracking-[-.08em] md:text-6xl">Less spreadsheet. More signal.</h2></div><div className="grid gap-x-10 gap-y-12 sm:grid-cols-2"><Feature icon={CircleDollarSign} title="One clean overview" copy="Income, expenses, and the number that matters most: what you get to keep." /><Feature icon={LineChart} title="Patterns, not panic" copy="Watch your month take shape. Spot the categories quietly asking for attention." /><Feature icon={Sparkles} title="A second perspective" copy="Ask for a plain-English summary when you want help reading between the lines." /><Feature icon={ArrowDownRight} title="Small moves count" copy="Every saved transaction is a vote for the life you are building." /></div></div></section>
         <section className="mx-5 mb-10 overflow-hidden rounded-[2rem] border border-[hsl(var(--secondary)/.35)] bg-[hsl(var(--primary)/.12)] px-6 py-14 md:mx-auto md:max-w-7xl md:px-16 md:py-20"><div className="flex flex-col items-start justify-between gap-10 md:flex-row md:items-end"><div><p className="mono-font text-xs font-bold uppercase tracking-[.18em] text-[hsl(var(--secondary))]">Start where you are</p><h2 className="display-font mt-4 max-w-xl text-5xl font-bold leading-[.94] tracking-[-.07em] md:text-7xl">Your money deserves a better readout.</h2></div><Link href="/sign-up" className="group flex shrink-0 items-center gap-3 rounded-xl bg-primary px-5 py-3.5 text-sm font-bold text-primary-foreground shadow-[0_0_25px_hsl(var(--primary)/.22)] transition-transform hover:-translate-y-1" data-testid="link-bottom-start">Make it clear <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link></div></section>
      </main>
      <footer className="mx-auto flex max-w-7xl items-center justify-between px-5 py-8 text-xs text-muted-foreground md:px-8"><BrandMark /><span>Made for the month ahead.</span></footer>
    </div>
  );
}

function Feature({ icon: Icon, title, copy }: { icon: typeof CircleDollarSign; title: string; copy: string }) {
  return <div className="group"><div className="grid h-10 w-10 place-items-center rounded-xl border border-[hsl(var(--secondary)/.35)] bg-[hsl(var(--secondary)/.1)] text-[hsl(var(--secondary))] transition-transform group-hover:-translate-y-1"><Icon className="h-5 w-5" /></div><h3 className="mt-4 text-lg font-bold">{title}</h3><p className="mt-2 max-w-xs text-sm leading-relaxed text-muted-foreground">{copy}</p></div>;
}